### ISSUE TITLE
几点建议与愿景

### ISSUE THREAD

**Issue by wsq93** [fanaiai/xndatepicker#15]
看了样例感觉非常棒！
希望这个项目能够在国内gitee网站上同步；
这个有没有建立开发咨询群什么的；
日历包含农历；
建立发行压缩包（我刚刚试着下载压缩包居然不行）；
i18n；
webJars发行。

**Comment by wsq93** [comment]
xndatepicker.min.js好像有点大，能再压缩就好了

**Comment by fanaiai** [comment]
> xndatepicker.min.js好像有点大，能再压缩就好了

多谢支持，容我忙过这阵就继续更新 @wsq93
